//! 记账图标白名单：分类/账户存的是 lucide 图标名字符串（同步与 Excel 都只带名字），
//! 界面在这里把名字换回组件。名字不在白名单里就回退到按类型/按侧的默认图标——
//! 老数据或手填的怪名字不该让界面开天窗。

import {
  Activity,
  Apple,
  Armchair,
  ArrowLeftRight,
  AtSign,
  Award,
  Baby,
  Backpack,
  BadgeDollarSign,
  BadgePercent,
  Bandage,
  Banknote,
  BanknoteArrowUp,
  Barcode,
  Bath,
  BedDouble,
  Beer,
  Bell,
  Bike,
  Bird,
  Bitcoin,
  Bluetooth,
  Bone,
  BookMarked,
  BookOpen,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Bus,
  Cake,
  Calculator,
  CalendarDays,
  Camera,
  Candy,
  Car,
  CarFront,
  Carrot,
  CarTaxiFront,
  Cat,
  ChartLine,
  Check,
  CircleAlert,
  CircleDollarSign,
  CircleDot,
  CircleHelp,
  Clapperboard,
  ClipboardList,
  Clock,
  Coffee,
  Coins,
  Compass,
  CookingPot,
  Cpu,
  CreditCard,
  Crown,
  CupSoda,
  Currency,
  Dog,
  DoorOpen,
  Droplet,
  Dumbbell,
  Ear,
  Ellipsis,
  Eye,
  FileText,
  Film,
  Filter,
  Fish,
  FishingRod,
  Flag,
  Flame,
  FlameKindling,
  Flower,
  Flower2,
  FolderOpen,
  Footprints,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Guitar,
  Handbag,
  HandCoins,
  HandFist,
  HandHeart,
  HandMetal,
  Handshake,
  HardDrive,
  HatGlasses,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  Home,
  Hospital,
  House,
  IceCreamCone,
  Info,
  Keyboard,
  KeyRound,
  Lamp,
  Landmark,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  Luggage,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  MemoryStick,
  MessageCircle,
  Mic,
  MirrorRound,
  Monitor,
  Moon,
  Motorbike,
  Mountain,
  Mouse,
  Music,
  Network,
  NotebookPen,
  Package,
  PackageOpen,
  Palette,
  Paperclip,
  PartyPopper,
  PawPrint,
  Pencil,
  PenLine,
  Percent,
  PersonStanding,
  Phone,
  PhoneCall,
  Piano,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  PlaneTakeoff,
  Plug,
  Presentation,
  Printer,
  Rabbit,
  Receipt,
  ReceiptText,
  Recycle,
  Ribbon,
  RotateCcw,
  Router,
  Ruler,
  Sailboat,
  Salad,
  Sandwich,
  Scale,
  School,
  Scissors,
  Send,
  Settings,
  Share2,
  ShieldPlus,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Signal,
  Sliders,
  Smartphone,
  Sofa,
  Soup,
  Sparkle,
  Sparkles,
  Speaker,
  SportShoe,
  Sprout,
  SquareParking,
  Squirrel,
  Star,
  Stethoscope,
  Store,
  Sun,
  Sunrise,
  Syringe,
  Tablet,
  Tag,
  Tags,
  Target,
  Tent,
  Thermometer,
  Ticket,
  Tickets,
  Timer,
  TrainFront,
  TramFront,
  TreePine,
  Trees,
  TrendingUp,
  Trophy,
  Truck,
  Turtle,
  Tv,
  Umbrella,
  Usb,
  UserRound,
  Users,
  Utensils,
  UtensilsCrossed,
  Vault,
  Volleyball,
  Wallet,
  Wallet2,
  WalletCards,
  Watch,
  Waves,
  Wifi,
  Wind,
  Wine,
  Worm,
  Wrench,
  Zap,
  type LucideIcon
} from "@lucide/svelte";
import type { LedgerAccountKind, LedgerSide } from "./types";

export const LEDGER_ICONS: Record<string, LucideIcon> = {
  Activity,
  Apple,
  Armchair,
  ArrowLeftRight,
  AtSign,
  Award,
  Baby,
  Backpack,
  BadgeDollarSign,
  BadgePercent,
  Bandage,
  Banknote,
  BanknoteArrowUp,
  Barcode,
  Bath,
  BedDouble,
  Beer,
  Bell,
  Bike,
  Bird,
  Bitcoin,
  Bluetooth,
  Bone,
  BookMarked,
  BookOpen,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Bus,
  Cake,
  Calculator,
  CalendarDays,
  Camera,
  Candy,
  Car,
  CarFront,
  Carrot,
  CarTaxiFront,
  Cat,
  ChartLine,
  Check,
  CircleAlert,
  CircleDollarSign,
  CircleDot,
  CircleHelp,
  Clapperboard,
  ClipboardList,
  Clock,
  Coffee,
  Coins,
  Compass,
  CookingPot,
  Cpu,
  CreditCard,
  Crown,
  CupSoda,
  Currency,
  Dog,
  DoorOpen,
  Droplet,
  Dumbbell,
  Ear,
  Ellipsis,
  Eye,
  FileText,
  Film,
  Filter,
  Fish,
  FishingRod,
  Flag,
  Flame,
  FlameKindling,
  Flower,
  Flower2,
  FolderOpen,
  Footprints,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Guitar,
  Handbag,
  HandCoins,
  HandFist,
  HandHeart,
  HandMetal,
  Handshake,
  HardDrive,
  HatGlasses,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  Home,
  Hospital,
  House,
  IceCreamCone,
  Info,
  Keyboard,
  KeyRound,
  Lamp,
  Landmark,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  Luggage,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  MemoryStick,
  MessageCircle,
  Mic,
  MirrorRound,
  Monitor,
  Moon,
  Motorbike,
  Mountain,
  Mouse,
  Music,
  Network,
  NotebookPen,
  Package,
  PackageOpen,
  Palette,
  Paperclip,
  PartyPopper,
  PawPrint,
  Pencil,
  PenLine,
  Percent,
  PersonStanding,
  Phone,
  PhoneCall,
  Piano,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  PlaneTakeoff,
  Plug,
  Presentation,
  Printer,
  Rabbit,
  Receipt,
  ReceiptText,
  Recycle,
  Ribbon,
  RotateCcw,
  Router,
  Ruler,
  Sailboat,
  Salad,
  Sandwich,
  Scale,
  School,
  Scissors,
  Send,
  Settings,
  Share2,
  ShieldPlus,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Signal,
  Sliders,
  Smartphone,
  Sofa,
  Soup,
  Sparkle,
  Sparkles,
  Speaker,
  SportShoe,
  Sprout,
  SquareParking,
  Squirrel,
  Star,
  Stethoscope,
  Store,
  Sun,
  Sunrise,
  Syringe,
  Tablet,
  Tag,
  Tags,
  Target,
  Tent,
  Thermometer,
  Ticket,
  Tickets,
  Timer,
  TrainFront,
  TramFront,
  TreePine,
  Trees,
  TrendingUp,
  Trophy,
  Truck,
  Turtle,
  Tv,
  Umbrella,
  Usb,
  UserRound,
  Users,
  Utensils,
  UtensilsCrossed,
  Vault,
  Volleyball,
  Wallet,
  Wallet2,
  WalletCards,
  Watch,
  Waves,
  Wifi,
  Wind,
  Wine,
  Worm,
  Wrench,
  Zap,
};

/** 一个图标分组：name 是中文展示名，icons 是 lucide 图标名（都在 LEDGER_ICONS 里）。 */
export interface LedgerIconGroup {
  readonly name: string;
  readonly icons: readonly string[];
}

/**
 * 图标分组目录，不含「全部」——「全部」由选择器把所有分组合并而成。
 * 这份分组同时被 Rust 侧 ledger_icons.rs 的目录镜像（由本文件生成）：
 * 加一个图标要三处一起动——顶部 import、LEDGER_ICONS 记录、以及恰好一个分组里。
 * 分组顺序 = 选择器分组 chips 的顺序；组内顺序 = 网格里的顺序。
 */
export const LEDGER_ICON_GROUPS: LedgerIconGroup[] = [
  { name: "饮食", icons: ["Utensils", "UtensilsCrossed", "Coffee", "CupSoda", "Candy", "Apple", "Carrot", "Cake", "IceCreamCone", "Wine", "Beer", "Soup", "Sandwich", "Pizza", "Salad", "Fish"] },
  { name: "娱乐", icons: ["Gamepad2", "Clapperboard", "Music", "Headphones", "Tv", "Film", "Palette", "Camera", "Guitar", "Piano", "PartyPopper", "Mic"] },
  { name: "购物", icons: ["ShoppingBag", "ShoppingCart", "Store", "ShoppingBasket", "Tag", "Tags", "Receipt", "PackageOpen", "Truck", "BadgePercent", "Barcode", "Gift"] },
  { name: "交通", icons: ["Bus", "Car", "CarFront", "CarTaxiFront", "TrainFront", "TramFront", "Plane", "Bike", "Fuel", "SquareParking", "Ship", "Motorbike"] },
  { name: "旅行", icons: ["Luggage", "Map", "MapPin", "Compass", "Globe", "Ticket", "Tickets", "Building2", "PlaneTakeoff", "Sunrise", "Umbrella"] },
  { name: "居住家具", icons: ["House", "KeyRound", "Wrench", "Zap", "Flame", "DoorOpen", "BedDouble", "Sofa", "Armchair", "Lamp", "Bath", "Lightbulb"] },
  { name: "家庭生活", icons: ["HeartHandshake", "Baby", "Users", "UserRound", "CookingPot", "Flower2", "Leaf", "Sprout", "Recycle", "HandHeart", "Home"] },
  { name: "医疗健康", icons: ["HeartPulse", "Pill", "Stethoscope", "Syringe", "Thermometer", "Activity", "Brain", "Eye", "Ear", "Hospital", "Bandage", "ShieldPlus"] },
  { name: "学习教育", icons: ["BookOpen", "PenLine", "GraduationCap", "BookMarked", "Library", "NotebookPen", "Pencil", "Ruler", "Calculator", "School", "Award"] },
  { name: "办公工作", icons: ["Briefcase", "FileText", "Printer", "ClipboardList", "FolderOpen", "Paperclip", "Monitor", "Laptop", "Presentation", "CalendarDays", "Clock", "Megaphone"] },
  { name: "通讯网络", icons: ["MessageCircle", "Wifi", "Phone", "PhoneCall", "Mail", "Send", "AtSign", "Network", "Router", "Signal", "Bluetooth", "Share2"] },
  { name: "金融理财", icons: ["Wallet", "Landmark", "CreditCard", "PiggyBank", "Coins", "TrendingUp", "ChartLine", "Percent", "Scale", "Bitcoin", "WalletCards", "Vault", "ReceiptText"] },
  { name: "收入", icons: ["BadgeDollarSign", "HandCoins", "Wallet2", "Medal", "Banknote", "BanknoteArrowUp", "RotateCcw", "CircleDollarSign", "Handshake", "Currency"] },
  { name: "运动健身", icons: ["Dumbbell", "PersonStanding", "Volleyball", "Trophy", "SportShoe", "Target", "Timer", "HandFist"] },
  { name: "个人护理", icons: ["Scissors", "Droplet", "Glasses", "Sun", "Moon", "Flower", "Heart", "HandMetal", "Sparkle", "MirrorRound"] },
  { name: "服饰美容", icons: ["Shirt", "Sparkles", "Brush", "Crown", "Footprints", "Watch", "Ribbon", "Handbag", "Gem", "HatGlasses"] },
  { name: "宠物", icons: ["Dog", "Bone", "PawPrint", "Cat", "Bird", "Rabbit", "Squirrel", "Turtle", "Bug", "Worm"] },
  { name: "数码", icons: ["Smartphone", "Tablet", "Mouse", "Keyboard", "HardDrive", "Cpu", "MemoryStick", "Usb", "Speaker", "Plug"] },
  { name: "运动户外", icons: ["Tent", "Mountain", "FlameKindling", "FishingRod", "Backpack", "TreePine", "Trees", "Waves", "Sailboat", "Wind"] },
  { name: "通用", icons: ["Package", "Ellipsis", "CircleDot", "Star", "Check", "Info", "CircleAlert", "CircleHelp", "Settings", "Sliders", "Filter", "Flag", "Bell", "ArrowLeftRight"] }
];

/** 图标选择网格的扁平名单：所有分组去重后的并集（「全部」chip 用它，也是 picker 顺序）。 */
export const LEDGER_ICON_CHOICES: string[] = LEDGER_ICON_GROUPS.flatMap(
  (group) => [...group.icons]
).filter((name, index, all) => all.indexOf(name) === index);

export const ACCOUNT_KIND_ICON: Record<LedgerAccountKind, string> = {
  cash: "Wallet",
  debit: "Landmark",
  credit: "CreditCard",
  investment: "PiggyBank",
  other: "WalletCards"
};

export const ACCOUNT_KIND_LABEL: Record<LedgerAccountKind, string> = {
  cash: "现金",
  debit: "储蓄卡",
  credit: "信用卡",
  investment: "投资",
  other: "其他"
};

export const ACCOUNT_KIND_COLOR: Record<LedgerAccountKind, string> = {
  cash: "#e8a33d",
  debit: "#b23a48",
  credit: "#c0392b",
  investment: "#2980b9",
  other: "#7f8c8d"
};

export function ledgerIcon(name: string | undefined, fallback: string): LucideIcon {
  if (name && LEDGER_ICONS[name]) return LEDGER_ICONS[name];
  return LEDGER_ICONS[fallback] ?? Ellipsis;
}

export function accountIconName(icon: string, kind: LedgerAccountKind): string {
  return icon && LEDGER_ICONS[icon] ? icon : ACCOUNT_KIND_ICON[kind];
}

function hexToRgb(color: string): [number, number, number] {
  const text = color.trim().replace("#", "");
  const full =
    text.length === 3
      ? text
          .split("")
          .map((part) => part + part)
          .join("")
      : text;
  if (!/^[0-9a-fA-F]{6}$/.test(full)) return [148, 163, 184];
  return [
    Number.parseInt(full.slice(0, 2), 16),
    Number.parseInt(full.slice(2, 4), 16),
    Number.parseInt(full.slice(4, 6), 16)
  ];
}

/**
 * 分类色的淡底（图标圆片的背景）：与白色混一下，饱和色不会在卡片上喧宾夺主。
 * 手写混色而不是 CSS `color-mix()`——Linux 上的旧 WebKitGTK 没有它。
 */
export function softColor(color: string, ratio = 0.15): string {
  const [r, g, b] = hexToRgb(color);
  const mix = (channel: number): string =>
    Math.round(channel * ratio + 255 * (1 - ratio))
      .toString(16)
      .padStart(2, "0");
  return `#${mix(r)}${mix(g)}${mix(b)}`;
}

/** 收支两侧的默认强调色：支出红、收入绿（热力图与统计图同口径）。 */
export const SIDE_COLOR: Record<LedgerSide, string> = {
  expense: "#d9534f",
  income: "#2f9e6e"
};

export const SIDE_LABEL: Record<LedgerSide, string> = {
  expense: "支出",
  income: "收入"
};

export const TRANSFER_ICON = "ArrowLeftRight";
